os: linux
language: go

go:
  - 1.16.2

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE go;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'postgres';" -U postgres

env:
  - APP_DB_USERNAME=postgres APP_DB_PASSWORD=postgres APP_DB_NAME=go

script:
  - go test -v ./...
  - CGO_ENABLED=0 GOARCH=amd64 go build -o go-mux