os: linux
language: go

go:
  - 1.16.2

services:
  - postgresql
  - docker

before_script:
  - psql -c "CREATE DATABASE go;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'postgres';" -U postgres

env:
  - APP_DB_HOST=localhost APP_DB_USERNAME=postgres APP_DB_PASSWORD=postgres APP_DB_NAME=go

script:
  - go test -v ./...
  - CGO_ENABLED=0 GOARCH=amd64 go build -o go-mux
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t jakobstadlhuber/go-mux:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag jakobstadlhuber/go-mux:latest jakobstadlhuber/go-mux:$GIT_SHA
  - docker push jakobstadlhuber/go-mux:latest
  - docker push jakobstadlhuber/go-mux:$GIT_SHA